- name: Setup Infra
  hosts: localhost
  tasks:
  - include_role:
      name: "infra/setup"
    vars:
      setup_action: 'create'
      setup_args:
        pool_name: default
        pool_path: "/var/lib/libvirt/images"
        node_count: 3
        node_memory: 3
        node_vcpu_count: 2
        node_name_prefix: "bm_node_"
        pool_name: default
        node_vol_size: 50

  - name: start sushy emulator
    vars:
      SUSHY_PORT: "{{ REDFISH_PORT | default('8001') }}"
      SUSHY_IP: "{{ REDFISH_PORT | default('0.0.0.0') }}"
    docker_container:
      restart: yes
      state: started
      network_mode: host
      privileged: yes
      detach: yes
      name: sushy-tools
      image: quay.io/metal3-io/sushy-tools
      command: 'sushy-emulator -i {{ SUSHY_IP }} -p {{ SUSHY_PORT }}'
      devices: "/dev/kvm:/dev/kvm"
      volumes:
        - /dev/kvm:/dev/kvm
        - /var/run/libvirt/libvirt-sock-ro:/var/run/libvirt/libvirt-sock-ro
        - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      env:
        FLASK_ENV: development

  - include_role:
      name: "bootstrap_node"
    vars:
      bootstrap_node_action: 'create'
      bootstrap_node_args:
        node_name: bm_node_0
        node_ip: "172.22.0.2"
        iso_path: "http://artifactory.nordix.org/artifactory/airship/k8s_iso/bm_dev_env/k8s_bootstrap.iso"
        iso_ssh_pub_key: "http://artifactory.nordix.org/artifactory/airship/k8s_iso/bm_dev_env/devuser_key.pub"
        iso_ssh_priv_key: "http://artifactory.nordix.org/artifactory/airship/k8s_iso/bm_dev_env/devuser_key"
        local_path: /tmp
        force_download: yes

