- name: Setup Infra
  hosts: localhost
  vars_files:
    - vars/defaults.yml
    - "{{ vars_file }}"
    - vars/vars_merge.yml
  tags:
    - infra
  tasks:
  - debug: var=params
  - include_role:
      name: "infra/setup"
    vars:
      setup_action: 'create'
      setup_args:
        pool_name: "{{ params.infra.libvirt_pool_name }}"
        pool_path: "{{ params.infra.libvirt_pool_path }}"
        node_count: "{{ params.infra.node_count }}"
        node_memory: "{{ params.infra.node_memory }}"
        node_vcpu_count: "{{ params.infra.node_vcpu_count }}"
        node_name_prefix: "{{ params.infra.node_name_prefix }}"
        node_vol_size: "{{ params.infra.node_vol_size }}"

  - name: start sushy emulator
    vars:
      SUSHY_PORT: "{{ params.redfish_server.port }}"
      SUSHY_IP: "{{ params.redfish_server.ip }}"
    docker_container:
      restart: yes
      state: started
      network_mode: host
      privileged: yes
      detach: yes
      name: sushy-tools
      image: quay.io/metal3-io/sushy-tools
      command: 'sushy-emulator -i {{ SUSHY_IP }} -p {{ SUSHY_PORT }}'
      devices: "/dev/kvm:/dev/kvm"
      volumes:
        - /dev/kvm:/dev/kvm
        - /var/run/libvirt/libvirt-sock-ro:/var/run/libvirt/libvirt-sock-ro
        - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      env:
        FLASK_ENV: development

- name: Start Bootstrap Cluster
  hosts: localhost
  tags:
    - bootstrap
  vars_files:
    - vars/defaults.yml
    - "{{ vars_file }}"
    - vars/vars_merge.yml
  tasks:
  - include_role:
      name: "bootstrap_node"
    vars:
      bootstrap_node_action: 'create'
      bootstrap_node_args:
        node_name: bm_node_0
        node_ip: "172.22.0.2"
        iso_path: "{{ params.bootstrap.iso_path }}"
        iso_ssh_pub_key: "{{ params.bootstrap.pub_key_path }}"
        iso_ssh_priv_key: "{{ params.bootstrap.priv_key_path }}"
        local_path: "{{ params.common.output_dir }}"
        force_download: "{{ params.bootstrap.force_iso_download }}"


